### ISSUE TITLE
Integration: CryptloCEX

### ISSUE THREAD

**Issue by SICCoin** [coinranking/exchanges#34]
**Exchange name**
CryptloCEX

**Website**
CryptloCEX.com

**API endpoint**
https://trade.cryptlocex.com/Api/Index/marketInfo

**API documentation**
https://documenter.getpostman.com/view/9600542/SWDze1WE?version=latest

**Comment by SICCoin** [comment]
Hello,

Thank you for your response. Will i be able to search for cryptlicex on
yourwebsite and can track listed tokens? Also do i need to do anything else
from our end?

Thanks

**Comment by nickpater** [comment]
Thank you for creating the issue and your response!

CryptloCEX will be automatically added to Coinranking in the coming days by our content team! The cryptocurrencies that are available on the exchange will also be automatically added if they have some volume. But that could take some time because of the huge backlist.

If you want to speed-up the listing of the tokens you could checkout this page: [https://coinranking.com/page/list-a-cryptocurrency](https://coinranking.com/page/list-a-cryptocurrency)

**Comment by SICCoin** [comment]
Hello Nick,

I see that new version has been release. I CryptloCEX.com added in this
version?

Thanks
